use_frameworks!

platform :ios, '8.0'

target 'RFTabbarControllerAnimationManger_Example' do
  pod 'RFTabbarControllerAnimationManger', :path => '../'

  target 'RFTabbarControllerAnimationManger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
